version: '3.8'
services:
  mysql:
    container_name: module_db
    restart: always
    image: mysql:latest   
    environment:
      - MYSQL_DATABASE=modules
      - MYSQL_USER=loginMySql
      - MYSQL_PASSWORD=secret654
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined      
    volumes:
      - dbdata:/var/lib/mysql
volumes:
    dbdata:      